### ISSUE TITLE
npm package incorrectly published

### ISSUE THREAD

**Issue by cusxio** [withspectrum/draft-js-markdown-plugin#123]
## Current Behaviour

https://unpkg.com/draft-js-markdown-plugin@3.0.2/lib/index.js

If you look into the source code for `v3.0.2`, the `handlePastedText` logic is still there despite being [removed](https://github.com/withspectrum/draft-js-markdown-plugin/pull/93). Which suggests that the package is incorrectly published !

Here's the diff between `v3.0.2` and `v2.1.2`

- https://www.diffchecker.com/WcQkwJcL

**Comment by mxstbr** [comment]
Oh crap that's why none of the fixes are in there what on earth! Digging in, thanks for the heads up
