### ISSUE TITLE
Dosen't work as expected

### ISSUE THREAD

**Issue by sookcha** [withspectrum/draft-js-markdown-plugin#137]
First of all, thanks for writing this plugin. It is an excellent work.

I'm using Redux for managing states, so I wrote like this:

```
// .jsx
                <Editor
                  editorState={editor.editorState}
                  onChange={actions.onSaveEditorState}
                  plugins={editor.plugins}
                />
```

```
// reducer
const defaultState = {
  editorState: EditorState.createEmpty(),
  plugins: [createMarkdownPlugin()]
};

  if (type === UPDATE_EDITOR_STATE) {
    newState = {
      ...state,
      editorState: payload
    };
 else if (type === UPDATE_EDITOR_CONTENT) {
    const text = fs.readFileSync(payload, 'utf8');
    newState = {
      ...state,
      editorState: EditorState.createWithContent(
        ContentState.createFromText(text),
      ),
      plugins: [createMarkdownPlugin()],
      currentFile: payload
    };
  }
```

It dose not work at all. The `editor.plugins` properly contains `draft-js-markdown-plugin` plugin in .jsx but it does not work. What is wrong with my code?

**Comment by mxstbr** [comment]
You're re-creating the plugin on every render, I think that might be it? Try instantiating it once in a variable and then passing that in `plugins`

**Comment by sookcha** [comment]
@mxstbr Well, I re-wrote like
```
const markdownPlugin = createMarkdownPlugin();
const defaultState = {
  editorState: EditorState.createEmpty(),
  plugins: [markdownPlugin]
};
```

But it's same

**Comment by mxstbr** [comment]
Hmm, not sure then unfortunately, I've never put my editorState into Redux! The plugin works for us so it must be something on your end in the combination with Redux 🤷‍♂️
