### ISSUE TITLE
disable inline styling in links

### ISSUE THREAD

**Issue by Rosey** [withspectrum/draft-js-markdown-plugin#14]
e.g. Entering a link draft-js-linkify-plugin link with underscores in its url converts the url to a link correctly but then also switches the underscores to italic, which is no good! (This is an issue in the original plugin as well but it seems like that one isn't being maintained much these days so I thought I'd file it here. Thinking about switching over :) )

May fork and fix this myself and PR if I have time but wanted a record of the bug somewhere in case I don't have time!

**Comment by mxstbr** [comment]
You are very right that's super annoying! It'd be awesome if you could submit a PR for that :heart:

**Comment by mxstbr** [comment]
Hey @Rosey any chance you got around to fixing this?

**Comment by Rosey** [comment]
No :( sorry! And I probably won't in the foreseeable future since I had a baby in January and don't have a lot of free time these days 😳

**Comment by mxstbr** [comment]
No worries at all. Congratulations, enjoy your remaining maternity leave! :sparkles:
