### ISSUE TITLE
How to output the state as Markdown?

### ISSUE THREAD

**Issue by rickitan** [withspectrum/draft-js-markdown-plugin#142]
Hi @mxstbr  and @andrewfan,

Awesome plugin! It's so powerful.

Question. How can I export the editor state as Markdown? And then how can initialize it with markdown?

What I'm trying to do is store the text the user types as markdown in the server, and then retrieve it and render it in the editor.

Thank you for the awesome work!
-Ricardo.

**Comment by mxstbr** [comment]
You should use one of the various "DraftJS state to markdown" packages! https://github.com/Rosey/markdown-draft-js https://www.npmjs.com/package/draftjs-to-markdown https://www.npmjs.com/package/markdown-draft-js etc.

Just google around a bit
