### ISSUE TITLE
Markdown not applied on enter in some cases

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/draft-js-markdown-plugin#15]
Smalzner just hit a bug where he was typing

```md
**bold**

```

Yet it wasn't applying the markdown. Seems to be a bug?

**Comment by aanchalgera** [comment]
Facing the same issue

**Comment by aanchalgera** [comment]
Worked for me if I keep this plugin as the first plugin in the plugin array :)

**Comment by mxstbr** [comment]
Ohh that's a good point, another plugin might've blocked that! Thanks for investigating, we should add that to the README. PR maybe?

**Comment by mxstbr** [comment]
Can't repro anymore, doesn't seem to be an actual bug. Closing!
