### ISSUE TITLE
Can I get the header-one text from editor

### ISSUE THREAD

**Issue by tageecc** [withspectrum/draft-js-markdown-plugin#159]
Which i need to auto-gengrate the article's title

thx~

**Comment by mxstbr** [comment]
You want to iterate through the `rawContentState.blocks` to find the one with the `type === 'header-one'` I think!

**Comment by tageecc** [comment]
> You want to iterate through the `rawContentState.blocks` to find the one with the `type === 'header-one'` I think!

yeah! you are right. thank you very much!
