### ISSUE TITLE
Getting plain (formatted) text?

### ISSUE THREAD

**Issue by z0al** [withspectrum/draft-js-markdown-plugin#16]
Hey, thank you all for this great plugin :) 

I've no idea how to get the original plain text. For example if you write `**bold**` and it gets styled then you only get `bold` when you call `getCurrentContent().getPlainText()`

**Demo**
![peek 2017-12-20 12-20](https://user-images.githubusercontent.com/12673605/34202655-1477ce96-e581-11e7-9cab-eacedfde64cb.gif)

Sorry if I'm asking on the wrong place.

**Comment by mxstbr** [comment]
This is the way DraftJS works! If you want to store this on the server you have to serialize the state to JSON (`convertToRaw`), then store that JSON, then convert back to state on the client (`convertFromRaw`) and render that with DraftJS. (or redraft) See this great post about the whole flow: https://reactrocket.com/post/draft-js-persisting-content/

If you want to store raw markdown on the server you'll have to convert the DraftJS state to Markdown, which you can do with https://www.npmjs.com/package/draft-js-export-markdown

Hope that clears some things up and helps!

**Comment by mxstbr** [comment]
...maybe we should add this to the docs, I'd appreciate a PR that adds this information nicely formatted to the README :blush:

**Comment by z0al** [comment]
Hey @mxstbr  thank you for your quick and valuable response :)

> we should add this to the docs

I will do a PR when I got something working :+1:

**Comment by mxstbr** [comment]
Also, I think @Rosey has an alternative to `draft-js-export-markdown` [here](https://github.com/Rosey/markdown-draft-js). I'm not entirely sure what the differences are, but you might want to try that too!

**Comment by z0al** [comment]
Both work well for the core styling stuff e.g. italic, bold ..etc but fail in links (especially images) and other cool features (I need) :/

I only need to convert Draft to Markdown string nothing more. I think I have to fork a project to implement the missing features

**Comment by Rosey** [comment]
https://github.com/Rosey/markdown-draft-js <-- the one that was mentioned that is mine allows you to extend the default functionality to support any entities or style items you need, so if it doesn't support something out of the box, it should be fairly simple to write a plugin for it (check out the readme, it gives instructions on writing plugins. Hopefully it's easy to understand)

If you think something should be part of the core functionality and isn't though, plz open an issue or a pr!

> I'm not entirely sure what the differences are, but you might want to try that too!

Re: this - basically I needed the "custom plugin" functionality that the other markdown converters didn't support, at least when I was looking into markdown converters. And I wanted a lib that went both ways (markdown to draft and draft to markdown) handling this custom stuff.

**Comment by mxstbr** [comment]
Makes total sense, seems to be a reasonable way of doing things. I'd like to add that to the readme instead of the other one then!

**Comment by z0al** [comment]
@Rosey Thanks, I will check the plugin docs :)
