### ISSUE TITLE
Add option to only allow certain markdown features

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/draft-js-markdown-plugin#21]
We need an option that only allows people to use inline markdown. (for messages) That would probably include:

- `**bold**`
- `*italic*`
- `inline code`
- `[links](http://example.com)`

**Comment by juliankrispel** [comment]
as in like a different `mode` of the plugin?

**Comment by mxstbr** [comment]
Yeah, or a whitelist of markdown features

**Comment by mxstbr** [comment]
Thinking about this a bit more, we'd probably actually want a whitelist of features to include so we can select what we want. Something like this:

```JS
createMarkdownPlugin({
  features: {
    inline: { bold: true, code: true },
    block: { code: true }
  }
})
```

Maybe?

**Comment by juliankrispel** [comment]
Okidokes!
