### ISSUE TITLE
Images don't load the first time, requires refresh

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/draft-js-markdown-plugin#22]
This is painfully hard to reproduce, but it happens quite often that you'll view a thread with images but the images never render. A refresh will fix this, or even just clicking into/out of a thread.

**Comment by juliankrispel** [comment]
hummm - there's no surefire way to repro this?

**Comment by brianlovin** [comment]
No, but I will try more tomorrow. Had some trouble with images this afternoon :)

**Comment by mxstbr** [comment]
Not a markdown plugin problem, that's all custom code

**Comment by brianlovin** [comment]
Gotcha, thanks!
