### ISSUE TITLE
Mixed inline styles bugs in 1.3.0

### ISSUE THREAD

**Issue by brianlovin** [withspectrum/draft-js-markdown-plugin#40]
Noticed these bugs in a 1.3.0 update: https://www.dropbox.com/s/yrcmvdohl8oclz6/draft-markdown-1.3.0.mov?dl=0

- mixing inline code and bold has unexpected behavior when closing the bold text, cursor repositions to inside the line
- mixing inline bold and italics jumps the cursor around and formats the text in unexpected places

Firefox 59.0.2, MacOS 10.13.3

**Comment by juliankrispel** [comment]
I think this is related to my updates

**Comment by juliankrispel** [comment]
fixed in #44
