### ISSUE TITLE
Exiting a code block

### ISSUE THREAD

**Issue by mxstbr** [withspectrum/draft-js-markdown-plugin#56]
Right now when you create a code block, there's no way to exit it apart from typing ```. (which is kinda unintuitive) Ideally there should be two more ways to do it:

- Automatically add an emtpy, unstyled block after a code block on creation so that one can downarrow to it
- On `SHIFT+Enter` jump out of the code block

I thought we had that first one already, but it appears to have been removed at some point. Any clues @juliankrispel?

**Comment by juliankrispel** [comment]
that's weird - yea we totally had that and I tested it :/

I'll make a pr
