### ISSUE TITLE
Pressing tab when in a list doesn't increase depth, unlike in the examples

### ISSUE THREAD

**Issue by jsindos** [withspectrum/draft-js-markdown-plugin#59]
I am using the basic example code from this project, and when pressing tab inside of a list, it doesn't increase the depth of the list, unlike the example hosted for this project.

Steps to reproduce:

![Image of Yaktocat](https://media.giphy.com/media/8FVyTkpqChRdfcRbpt/giphy.gif)

**Comment by michaelgmcd** [comment]
It appears that this works in the demo: https://markdown-plugin.spectrum.chat/

Can you reproduce it there?

**Comment by jsindos** [comment]
@michaelgmcd It appears I can no longer reproduce this issue locally. Issue closed; sorry for the false positive!
