### ISSUE TITLE
Checkboxes are not clickable if a code block exists

### ISSUE THREAD

**Issue by michaelgmcd** [withspectrum/draft-js-markdown-plugin#66]
Haven't been able to dive too deep into this

![checkbox-bug](https://user-images.githubusercontent.com/8161781/39399334-d8617a46-4ae9-11e8-82ea-f9d3f3bbd721.gif)

**Comment by michaelgmcd** [comment]
Looking into it further, it's the handling of clicking outside of the code block that prevents this. Specifically:
https://github.com/withspectrum/draft-js-markdown-plugin/blob/25fdebba49ef247164bca937af2e3a3d880e6dec/src/components/Code/index.js#L87

Not sure what this is exactly for or how to handle this properly.

**Comment by mxstbr** [comment]
That does basically nothing if I understand that code correctly? 🤔🤔🤔 Does anything break when you remove it? /cc @juliankrispel

**Comment by michaelgmcd** [comment]
It doesn't seem to break anything when that line of code is removed.

**Comment by andrewfan** [comment]
@mxstbr @michaelgmcd I think it was fixed by this PR https://github.com/withspectrum/draft-js-markdown-plugin/pull/78

**Comment by mxstbr** [comment]
Yep true, thank you for submitting that! :pray:
