### ISSUE TITLE
Insert Image as Atomic Block

### ISSUE THREAD

**Issue by cusxio** [withspectrum/draft-js-markdown-plugin#69]
## Situation

Currently, images are not inserted as atomic block which makes them incompatible with plugins from [`draft-js-plugins`](https://medium.com/@nikgraf/announcing-draftjs-plugins-2-0-8c25f2a4df55).

Are you open to insert image as atomic block?

I can provide a PR.

## Demo

![demo](https://user-images.githubusercontent.com/6487613/39627305-0b595bec-4fd8-11e8-8c1d-6d62cba70bf3.gif)

[**Demo**](http://abhorrent-ticket.surge.sh/) of this plugin working together with `draft-js-image-plugin` and `draft-js-focus-plugin`.

## Side Note

To make the demo above work, I needed to fork this library to change the image entity from `IMG` to `IMAGE`.

Since image is a non-standard block in `draft-js`, I think this plugin needs to provide a way to change the [image entity](https://github.com/withspectrum/draft-js-markdown-plugin/blob/9304310dfe101abf49eeaba8c7f97ce7dfefdde3/src/modifiers/insertImage.js#L14-L18).

Most libraries uses `IMAGE` instead of `IMG` too.

Plugins that uses `IMAGE`
- [`draft-js-image-plugin`](https://github.com/draft-js-plugins/draft-js-plugins/blob/master/draft-js-image-plugin/src/index.js#L24)
- [`draft-js-utils`](https://github.com/sstur/draft-js-utils/blob/master/packages/draft-js-utils/src/Constants.js#L22)

**Comment by mxstbr** [comment]
Yeah sure, that sounds good to me!
