### ISSUE TITLE
Create demo page

### ISSUE THREAD

**Issue by lambdafu** [withspectrum/draft-js-markdown-plugin#7]
The demo link in the README points to https://ngs.github.io/draft-js-markdown-plugin, which doesn't exist.  Maybe set up a static page like the original demo page to help people try out the differences between this and the original?  Thx!

**Comment by mxstbr** [comment]
Yeah, should definitely do that!

**Comment by mxstbr** [comment]
As a sidenote, all of the differences to the original plugin are outlined in the Changelog: https://github.com/withspectrum/draft-js-markdown-plugin/releases

Also, we'll keep up with changes that happen upstream and incorporate them into this fork (if any ever happen, that is), so not much can go wrong with using the fork :blush:

**Comment by mxstbr** [comment]
There you go, I improved the demo and deployed it again! https://markdown-plugin.spectrum.chat
