### ISSUE TITLE
Cursor jumps to line below when creating checklists

### ISSUE THREAD

**Issue by watlandc** [withspectrum/draft-js-markdown-plugin#72]
# Issue 

When creating a checklist `- [ ]` the cursor immediately jumps to the line below.  

# Expected behavior

The issue appears in `spectrum.chat` and in a separate test environment, but checklists work as expected in the `draft-js-markdown-plugin` demo:

https://markdown-plugin.spectrum.chat/

# Demo

**Spectrum.chat**

![markdown_checklist_bug](https://user-images.githubusercontent.com/6117504/39798511-7a38b0b6-5326-11e8-9039-7e8d52768add.gif)

**Separate environment**

![checkbox_bug](https://user-images.githubusercontent.com/6117504/39799120-b58bc6d8-5328-11e8-97ab-99f80c5ffd66.gif)

Perhaps `spectrum.chat` hasn't whitelisted the checklist feature, but the cursor jump appears in both cases.

# Browser

Browser: Chrome latest `Version 66.0.3359.139 (Official Build) (64-bit)`

Spectrum appears to be using version `"draft-js-markdown-plugin": "1.4.4"`

**Comment by mxstbr** [comment]
Yeah we haven't whitelisted or enabled the checkbox feature—not sure why it does that when it's disabled.

I think this has something to do with the blockMap, although I'm not 100% sure, I haven't dug into that code at all.

**Comment by andrewfan** [comment]
@watlandc @mxstbr  I guess it happens because styles for checkbox were not included 
markup for checkbox is 
```
<div>checkbox</div>
<div>text that you continue typing</div>
```
to fix this just import 
`import 'draft-js-checkable-list-item/lib/CheckableListItem.css';`

**Comment by watlandc** [comment]
Noted.  Thanks for the heads up!
