### ISSUE TITLE
this plugin blocks other plugins handlePastedText when pasting raw text 

### ISSUE THREAD

**Issue by andrewfan** [withspectrum/draft-js-markdown-plugin#85]
when we paste raw text (f.e copy website URL) `handlePastedText` of this plugin always handles it because of these lines https://github.com/withspectrum/draft-js-markdown-plugin/blob/master/src/index.js#L426

**Comment by mxstbr** [comment]
Yeah we should just remove that code, it breaks too many things unnecessarily. Ref #75
