### ISSUE TITLE
Proposal/question: should adding CODE inline style clean all styles inside selection?

### ISSUE THREAD

**Issue by andrewfan** [withspectrum/draft-js-markdown-plugin#96]
My question/proposal is should we remove all styles before applying inline CODE style?

**Comment by mxstbr** [comment]
Hmm, good question, not really sure. Maybe?

**Comment by andrewfan** [comment]
Currenly it is impossible to put markdown syntax in inline code block (because each time we put something that fits markdown inline regexp it will be converted to the styled entity)

**Comment by mxstbr** [comment]
> Currenly it is impossible to put markdown syntax in inline code block (because each time we put something that fits markdown inline regexp it will be converted to the styled entity)

We should probably filter code blocks from other inline calculations then? E.g.

```
Some `code with an _underscore` and here's some text with_ an underscore
```

Typing this should _not_ trigger italic text, right? Just like it doesn't on GitHub: Some `code with an _underscore` and here's some text with_ an underscore

**Comment by mxstbr** [comment]
> Currenly it is impossible to put markdown syntax in inline code block (because each time we put something that fits markdown inline regexp it will be converted to the styled entity)

We should probably filter code blocks from other inline calculations then? E.g.

```
Some `code with an _underscore` and here's some text with_ an underscore
```

Typing this should _not_ trigger italic text, right? Just like it doesn't on GitHub: Some `code with an _underscore` and here's some text with_ an underscore
