### ISSUE TITLE
Inline styles should not be applied in the middle of the word

### ISSUE THREAD

**Issue by andrewfan** [withspectrum/draft-js-markdown-plugin#98]
Those https://github.com/withspectrum/draft-js-markdown-plugin/blob/master/src/constants.js#L5 regexp should take into account word delimiter to avoid applying styles in the middle of the word.
E.g.
`this_is_the_file_name` should not be converted in `this[italic start]is[italic end]the[italic start]file[italic end]name`

**Comment by mxstbr** [comment]
Yeah I tried figuring this out for a bit but couldn't—would love a PR improving this!
